<?php
/**
 * Google Apps Script authentication bridge.
 *
 * Allows WordPress to validate users against a shared GAS endpoint and,
 * optionally, to let GAS apps trust a signed token generated by WordPress.
 *
 * Each Apps Script app must expose a doPost/equivalent endpoint that
 * accepts JSON with { action, email, token } and responds { success, user }.
 * See docs/gas-auth-bridge.md for the GAS-side code.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Arc_Portal_GAS_Auth_Bridge {

	/**
	 * Singleton instance.
	 *
	 * @var Arc_Portal_GAS_Auth_Bridge|null
	 */
	private static $instance = null;

	/**
	 * Option key for the shared GAS auth URL.
	 *
	 * @var string
	 */
	private $auth_url_option = 'arc_portal_app_gas_auth_url';

	/**
	 * Option key for the API secret used to sign tokens.
	 *
	 * @var string
	 */
	private $api_secret_option = 'arc_portal_app_gas_api_secret';

	/**
	 * Get the singleton instance.
	 *
	 * @return Arc_Portal_GAS_Auth_Bridge
	 */
	public static function instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Constructor.
	 */
	private function __construct() {
		add_action( 'rest_api_init', array( $this, 'register_rest_routes' ) );
		add_filter( 'authenticate', array( $this, 'authenticate_with_gas' ), 30, 3 );
		add_action( 'user_register', array( $this, 'sync_user_to_gas' ), 10, 1 );
		add_action( 'profile_update', array( $this, 'sync_user_to_gas' ), 10, 1 );
	}

	/**
	 * Get the configured GAS auth URL.
	 *
	 * @return string
	 */
	public function get_auth_url() {
		return get_option( $this->auth_url_option, '' );
	}

	/**
	 * Get the configured API secret.
	 *
	 * @return string
	 */
	public function get_api_secret() {
		return get_option( $this->api_secret_option, '' );
	}

	/**
	 * Register REST API routes.
	 */
	public function register_rest_routes() {
		register_rest_route(
			'arc-portal/v1',
			'/gas-auth/validate',
			array(
				'methods'             => 'POST',
				'callback'            => array( $this, 'rest_validate_user' ),
				'permission_callback' => '__return_true',
			)
		);

		register_rest_route(
			'arc-portal/v1',
			'/gas-auth/token',
			array(
				'methods'             => 'POST',
				'callback'            => array( $this, 'rest_get_token' ),
				'permission_callback' => function () {
					return is_user_logged_in();
				},
			)
		);
	}

	/**
	 * Try to authenticate a user against the GAS shared endpoint.
	 *
	 * @param WP_User|null $user Existing user object.
	 * @param string       $username Username or email.
	 * @param string       $password Password.
	 * @return WP_User|null
	 */
	public function authenticate_with_gas( $user, $username, $password ) {
		if ( $user instanceof WP_User ) {
			return $user;
		}

		$auth_url = $this->get_auth_url();
		if ( empty( $auth_url ) ) {
			return $user;
		}

		$email = sanitize_email( $username );
		if ( ! is_email( $email ) || empty( $password ) ) {
			return $user;
		}

		$response = $this->call_gas( 'authenticate', array( 'email' => $email, 'password' => $password ) );

		if ( ! empty( $response['success'] ) ) {
			$wp_user = get_user_by( 'email', $email );
			if ( $wp_user && wp_check_password( $password, $wp_user->user_pass, $wp_user->ID ) ) {
				return $wp_user;
			}

			if ( ! $wp_user && ! empty( $response['user'] ) ) {
				$wp_user = $this->create_user_from_gas( $email, $response['user'] );
				if ( $wp_user ) {
					return $wp_user;
				}
			}
		}

		return $user;
	}

	/**
	 * REST endpoint: validate a user email against GAS.
	 *
	 * @param WP_REST_Request $request REST request.
	 * @return WP_REST_Response|WP_Error
	 */
	public function rest_validate_user( $request ) {
		$params = $request->get_json_params();
		$email  = sanitize_email( $params['email'] ?? '' );

		if ( ! is_email( $email ) ) {
			return new WP_Error( 'invalid_email', __( 'Invalid email', 'arc-portal' ), array( 'status' => 400 ) );
		}

		$response = $this->call_gas( 'validate', array( 'email' => $email ) );

		if ( false === $response ) {
			return new WP_Error( 'gas_error', __( 'Error contacting Google Apps Script', 'arc-portal' ), array( 'status' => 500 ) );
		}

		return rest_ensure_response( $response );
	}

	/**
	 * REST endpoint: generate a signed token for the logged-in user.
	 *
	 * @param WP_REST_Request $request REST request.
	 * @return WP_REST_Response|WP_Error
	 */
	public function rest_get_token( $request ) {
		$user = wp_get_current_user();
		if ( ! $user->exists() ) {
			return new WP_Error( 'not_logged_in', __( 'Not authenticated', 'arc-portal' ), array( 'status' => 401 ) );
		}

		$token = $this->generate_token( $user );

		return rest_ensure_response( array(
			'success' => true,
			'token'   => $token,
			'email'   => $user->user_email,
			'expires' => time() + 300,
		) );
	}

	/**
	 * Generate a short-lived signed token for a user.
	 *
	 * @param WP_User $user WordPress user.
	 * @return string
	 */
	public function generate_token( $user ) {
		$secret = $this->get_api_secret();
		if ( empty( $secret ) ) {
			$secret = wp_salt( 'auth' );
		}

		$expires = time() + 300;
		$payload = $user->user_email . '|' . $expires . '|' . $user->ID;
		$hash    = hash_hmac( 'sha256', $payload, $secret );

		return $payload . '|' . $hash;
	}

	/**
	 * Verify a token generated by generate_token().
	 *
	 * @param string $token Token to verify.
	 * @return array|false
	 */
	public function verify_token( $token ) {
		$parts = explode( '|', $token );
		if ( count( $parts ) !== 4 ) {
			return false;
		}

		list( $email, $expires, $user_id, $token_hash ) = $parts;

		if ( ! is_email( $email ) || ! is_numeric( $user_id ) || (int) $expires < time() ) {
			return false;
		}

		$secret  = $this->get_api_secret();
		if ( empty( $secret ) ) {
			$secret = wp_salt( 'auth' );
		}

		$payload = $email . '|' . $expires . '|' . $user_id;
		$hash    = hash_hmac( 'sha256', $payload, $secret );

		if ( ! hash_equals( $hash, $token_hash ) ) {
			return false;
		}

		$user = get_user_by( 'email', $email );
		if ( ! $user || $user->ID !== (int) $user_id ) {
			return false;
		}

		return array(
			'email'   => $email,
			'user_id' => (int) $user_id,
			'expires' => (int) $expires,
		);
	}

	/**
	 * Sync a WordPress user to GAS on register/update.
	 *
	 * @param int $user_id WordPress user ID.
	 * @return bool
	 */
	public function sync_user_to_gas( $user_id ) {
		$user = get_userdata( $user_id );
		if ( ! $user ) {
			return false;
		}

		$auth_url = $this->get_auth_url();
		if ( empty( $auth_url ) ) {
			return false;
		}

		$response = $this->call_gas(
			'sync_user',
			array(
				'email'    => $user->user_email,
				'name'     => $user->display_name,
				'role'     => $this->map_wp_role_to_gas_role( $user->roles ),
				'active'   => true,
				'user_id'  => $user->ID,
			)
		);

		return ! empty( $response['success'] );
	}

	/**
	 * Call the shared GAS endpoint.
	 *
	 * @param string $action Action name.
	 * @param array  $data Additional payload.
	 * @return array|false
	 */
	private function call_gas( $action, $data = array() ) {
		$auth_url = $this->get_auth_url();
		if ( empty( $auth_url ) ) {
			return false;
		}

		$body = array_merge( array( 'action' => $action ), $data );

		$response = wp_remote_post(
			$auth_url,
			array(
				'body'    => wp_json_encode( $body ),
				'headers' => array( 'Content-Type' => 'application/json' ),
				'timeout' => 15,
			)
		);

		if ( is_wp_error( $response ) ) {
			if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
				error_log( 'ARC Portal GAS error: ' . $response->get_error_message() );
			}
			return false;
		}

		$body = wp_remote_retrieve_body( $response );
		$decoded = json_decode( $body, true );

		return is_array( $decoded ) ? $decoded : false;
	}

	/**
	 * Create a WordPress user from GAS user data.
	 *
	 * @param string $email Email address.
	 * @param array  $gas_user GAS user data.
	 * @return WP_User|false
	 */
	private function create_user_from_gas( $email, $gas_user ) {
		$username = sanitize_user( $email );
		$password = wp_generate_password( 16, true );

		$user_id = wp_create_user( $username, $password, $email );
		if ( is_wp_error( $user_id ) ) {
			if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
				error_log( 'ARC Portal create user error: ' . $user_id->get_error_message() );
			}
			return false;
		}

		$user = new WP_User( $user_id );
		$user->set_role( $this->map_gas_role_to_wp_role( $gas_user['role'] ?? 'viewer' ) );

		if ( ! empty( $gas_user['name'] ) ) {
			wp_update_user(
				array(
					'ID'           => $user_id,
					'display_name' => sanitize_text_field( $gas_user['name'] ),
				)
			);
		}

		wp_new_user_notification( $user_id, $password );

		return $user;
	}

	/**
	 * Map WP roles to GAS roles.
	 *
	 * @param array $wp_roles WordPress roles.
	 * @return string
	 */
	private function map_wp_role_to_gas_role( $wp_roles ) {
		if ( in_array( 'administrator', (array) $wp_roles, true ) ) {
			return 'admin';
		}
		if ( in_array( 'editor', (array) $wp_roles, true ) ) {
			return 'manager';
		}
		return 'viewer';
	}

	/**
	 * Map GAS roles to WP roles.
	 *
	 * @param string $gas_role GAS role.
	 * @return string
	 */
	private function map_gas_role_to_wp_role( $gas_role ) {
		switch ( $gas_role ) {
			case 'admin':
				return 'administrator';
			case 'manager':
				return 'editor';
			case 'viewer':
			default:
				return 'subscriber';
		}
	}
}
